import { ArrowLeft, ChevronLeft, ChevronRight, ShoppingBag, Truck, RotateCcw, BadgeCheck, Sparkles } from "lucide-react";
import { useRef } from "react";
import { Link, useNavigate } from "react-router-dom";
import { getProductName, getProductPrice, ProductCard, useStore, type StoreProduct } from "@/components/store/StoreLayout";

const collectionTiles = [
  { label: "New Collection", category: "", image: "https://glowmodest.com/cdn/shop/files/1243.jpg?v=1783539357&width=800" },
  { label: "Sets", category: "Sets", image: "https://glowmodest.com/cdn/shop/files/32435.jpg?v=1783539453&width=800" },
  { label: "Blouses / shirts", category: "Blouses / shirts", image: "https://glowmodest.com/cdn/shop/files/sadas.jpg?v=1783539640&width=800" },
  { label: "Skirts / pants", category: "Skirts / pants", image: "https://glowmodest.com/cdn/shop/files/3423.jpg?v=1783539838&width=800" },
  { label: "Denims", category: "Denims", image: "https://glowmodest.com/cdn/shop/files/lklk.jpg?v=1783540056&width=800" },
  { label: "Dresses", category: "Dresses", image: "https://images.unsplash.com/photo-1566174053879-31528523f8ae?auto=format&fit=crop&w=850&q=85" },
];

const styleStories = [
  { title: "Khaki set", video: "https://videos.pexels.com/video-files/9218181/9218181-hd_1920_1080_30fps.mp4", image: "https://images.unsplash.com/photo-1551488831-00ddcb6c6bd3?auto=format&fit=crop&w=900&q=90" },
  { title: "Ribbed black top", video: "https://videos.pexels.com/video-files/36726516/15565099_360_640_30fps.mp4", image: "https://images.unsplash.com/photo-1608234807905-4466023792f5?auto=format&fit=crop&w=900&q=90" },
  { title: "No name look", video: "https://videos.pexels.com/video-files/9218081/9218081-sd_960_540_30fps.mp4", image: "https://images.unsplash.com/photo-1539109136881-3be0616acf4b?auto=format&fit=crop&w=900&q=90" },
  { title: "White linen shirt", video: "https://videos.pexels.com/video-files/3888260/3888260-sd_426_226_25fps.mp4", image: "https://images.unsplash.com/photo-1529139574466-a303027c1d8b?auto=format&fit=crop&w=900&q=90" },
];

function CategoryShelfCard({ product, index }: { product: StoreProduct; index: number }) {
  const { language, addToCart, cartItems, liked, toggleLike } = useStore();
  const navigate = useNavigate();
  const added = cartItems.some((item) => item.product.id === product.id);
  const productName = getProductName(product, language);
  const openProduct = () => navigate(`/product/${product.id}`);
  return <article role="link" tabIndex={0} onClick={openProduct} onKeyDown={(event) => { if (event.key === "Enter" || event.key === " ") openProduct(); }} className="relative aspect-[.8] w-full shrink-0 cursor-pointer overflow-hidden bg-white shadow-[1px_1px_10px_rgba(0,0,0,.3)] transition duration-500 ease-out hover:z-10 hover:-translate-y-2 hover:scale-[1.02]"><Link to={`/product/${product.id}`} className="absolute inset-0 z-[1]" aria-label={productName} /><img src={product.image} alt={productName} loading="lazy" className="absolute inset-0 h-full w-full object-cover" /><button type="button" onPointerDown={(event) => event.stopPropagation()} onClick={(event) => { event.stopPropagation(); toggleLike(index); }} className="absolute left-4 top-4 z-[3] text-xl" aria-label={language === "en" ? "Add to wishlist" : "إضافة للمفضلة"}><span className={liked.includes(index) ? "text-[#d4775c]" : "text-white drop-shadow"}>♥</span></button><div className="pointer-events-none absolute inset-x-0 bottom-0 z-[2] bg-gradient-to-t from-black/65 via-black/20 to-transparent px-5 pb-5 pt-20 text-left text-white sm:px-8 sm:pb-6"><h3 className="text-[15px] font-light uppercase tracking-[0.12em] text-white drop-shadow-[0_2px_10px_rgba(0,0,0,.45)] sm:text-[18px]">{productName}</h3><p className="mt-1 text-[11px] tracking-[0.08em]">{getProductPrice(product, language)}</p><button type="button" onPointerDown={(event) => event.stopPropagation()} onClick={(event) => { event.stopPropagation(); addToCart(product); }} className={`pointer-events-auto relative z-[3] mt-2 inline-flex h-9 w-9 items-center justify-center rounded-full text-black transition hover:bg-white ${added ? "bg-black text-white" : "bg-[#e8e3db]"}`} aria-label={language === "en" ? "Add to cart" : "إضافة إلى السلة"}><ShoppingBag size={15} strokeWidth={1.5} /></button></div></article>;
}

function CollectionShelf({ title, description, items, linkLabel }: { title: string; description?: string; items: StoreProduct[]; linkLabel: string }) {
  const shelfRef = useRef<HTMLDivElement>(null);
  const dragRef = useRef({ active: false, startX: 0, scrollLeft: 0 });
  if (!items.length) return null;
  const scrollShelf = (direction: number) => shelfRef.current?.scrollBy({ left: direction * Math.max(280, shelfRef.current.clientWidth * 0.72), behavior: "smooth" });
  const startDrag = (event: React.PointerEvent<HTMLDivElement>) => { if (!shelfRef.current || (event.target as HTMLElement).closest("button, a")) return; dragRef.current = { active: true, startX: event.clientX, scrollLeft: shelfRef.current.scrollLeft }; event.currentTarget.setPointerCapture(event.pointerId); };
  const moveDrag = (event: React.PointerEvent<HTMLDivElement>) => { if (!dragRef.current.active || !shelfRef.current) return; shelfRef.current.scrollLeft = dragRef.current.scrollLeft - (event.clientX - dragRef.current.startX); };
  const stopDrag = () => { dragRef.current.active = false; };
  return <section className="bg-white px-5 py-16 lg:px-8 lg:py-20"><div className="mx-auto max-w-[1240px]"><div className="mb-9 flex items-end justify-between"><div className="mx-auto text-center"><h2 className="font-serif text-4xl tracking-[-0.04em] sm:text-5xl">{title}</h2>{description && <p className="mt-3 text-[12px] text-black/50">{description}</p>}</div><div className="flex gap-2"><button type="button" onClick={() => scrollShelf(-1)} className="flex h-9 w-9 items-center justify-center rounded-full border border-black/15" aria-label="السابق"><ChevronRight size={17} /></button><button type="button" onClick={() => scrollShelf(1)} className="flex h-9 w-9 items-center justify-center rounded-full border border-black/15" aria-label="التالي"><ChevronLeft size={17} /></button></div></div><div ref={shelfRef} onPointerDown={startDrag} onPointerMove={moveDrag} onPointerUp={stopDrag} onPointerCancel={stopDrag} onPointerLeave={stopDrag} className="-mx-5 flex snap-x snap-mandatory gap-0 overflow-x-auto px-5 pb-4 [scrollbar-width:none] cursor-grab select-none active:cursor-grabbing touch-pan-x">{items.map((product, index) => <div key={product.id} className="-ml-8 min-w-[78%] snap-center sm:min-w-[42%] lg:min-w-[31%] first:ml-0"><CategoryShelfCard product={product} index={index} /></div>)}</div><div className="mt-10 text-center"><Link to={`/shop?category=${items[0].category}`} className="inline-flex rounded-full bg-black px-8 py-3 text-[11px] font-bold text-white transition hover:bg-[#d8c799] hover:text-black">{linkLabel}</Link></div></div></section>;
}

export default function Index() {
  const { catalog, language, sections, siteSettings } = useStore();
  const isEnglish = language === "en";
  const jackets = catalog.filter((product) => product.category === "جاكيتات");
  const sets = catalog.filter((product) => product.category === "أطقم" || product.category === "Sets");
  const tops = catalog.filter((product) => product.category === "توبس" || product.category === "Blouses / shirts");
  const pants = catalog.filter((product) => product.category === "بنطال" || product.category === "Skirts / pants");
  const dresses = catalog.filter((product) => product.category === "فساتين" || product.category === "Dresses");
  const localizedTiles = collectionTiles.map((tile, index) => ({ ...tile, label: ["New Collection", "Sets", "Blouses / shirts", "Skirts / pants", "Denims", "Dresses"][index] }));
  const localizedStories = styleStories.map((story, index) => ({ ...story, video: siteSettings.discoverVideos?.[index] || story.video, title: isEnglish ? ["Khaki set", "Ribbed black top", "No name look", "White linen shirt"][index] : story.title }));
  return <>
    <section className="relative h-[598px] w-full overflow-hidden bg-[#1c2822] text-white" style={{ "--brand-accent": siteSettings.accent } as React.CSSProperties}><div className="absolute inset-0"><img src="https://glowmodest.com/cdn/shop/files/1P0A2473.jpg?v=1784649698&width=2000" alt="تشكيلة no name لصيف 2026" loading="eager" className="h-full w-full object-cover object-center" /></div><div className="absolute inset-0 bg-black/25" /><div dir={isEnglish ? "ltr" : "rtl"} className={`absolute bottom-[15%] left-[6%] z-10 max-w-[500px] sm:left-[10%] ${isEnglish ? "text-left" : "text-right"}`}><h1 className="mb-5 font-sans text-5xl font-extrabold leading-[1.1] tracking-[0.01em] sm:text-[70px]">{siteSettings.heroTitle || (isEnglish ? "New for Summer 2026" : "جديد في صيف 2026")}</h1><p className="mb-8 text-base font-light leading-8 tracking-wide sm:text-lg">{siteSettings.heroDescription || (isEnglish ? "Modest styles designed for everyday comfort." : "أزياء محتشمة، مصممة لراحة الحياة اليومية.")}</p><Link to="/shop" className="inline-flex border border-white px-7 py-3.5 text-[11px] font-semibold tracking-[0.08em] transition hover:bg-white hover:text-[#1c2822] sm:px-10 sm:py-4" style={{ borderColor: siteSettings.accent }}>{isEnglish ? "Shop new arrivals" : "تسوقي المنتجات الجديدة"}</Link></div></section>
    <section className="bg-white px-5 py-16 lg:px-8 lg:py-20"><div className="mx-auto max-w-[1240px]"><h2 className="mb-9 text-center font-sans text-4xl tracking-[-0.04em] sm:text-5xl">{sections.arrivals?.title || "New Collection"}</h2>{sections.arrivals?.description && <p className="-mt-5 mb-9 text-center text-[12px] text-black/50">{sections.arrivals.description}</p>}<div className="-mx-5 flex snap-x snap-mandatory gap-3 overflow-x-auto px-5 pb-3 [scrollbar-width:none] sm:mx-0 sm:grid sm:grid-cols-3 sm:gap-x-3 sm:gap-y-10 sm:overflow-visible sm:px-0 sm:pb-0 lg:grid-cols-4 lg:gap-5">{catalog.slice(0, 8).map((product, index) => <div key={product.id} className="min-w-[78%] snap-start sm:min-w-0"><ProductCard product={product} index={index} /></div>)}</div><div className="mt-12 text-center"><Link to="/shop" className="inline-flex items-center gap-3 text-[13px] font-medium">{isEnglish ? "Shop new arrivals" : "تسوق أحدث المنتجات"} <ArrowLeft size={17} /></Link></div></div></section>
    <section className="bg-white px-5 py-14 lg:px-8 lg:py-20"><div className="mx-auto max-w-[1240px]"><h2 className="mb-3 text-center font-serif text-4xl tracking-[-0.04em] sm:text-5xl">{sections.categories?.title || "Shop by category"}</h2>{sections.categories?.description && <p className="mb-10 text-center text-[12px] text-black/50">{sections.categories.description}</p>}<div className="grid grid-cols-2 gap-4 sm:grid-cols-3 lg:grid-cols-6 lg:gap-5">{localizedTiles.map((tile) => <Link key={tile.label} to={tile.category ? `/shop?category=${tile.category}` : "/shop"} className="group relative aspect-[3/4] overflow-hidden bg-[#eeeeee]"><img src={tile.image} alt={tile.label} loading="lazy" className="h-full w-full object-cover transition duration-700 ease-out group-hover:scale-105" /><div className="absolute inset-0 bg-black/0 transition duration-500 group-hover:bg-black/45" /><div className="absolute inset-0 flex flex-col items-center justify-center gap-2 p-4 text-center text-white"><span className="text-lg font-light tracking-[0.08em] drop-shadow-[0_2px_10px_rgba(0,0,0,.45)]">{tile.label}</span><span className="h-0.5 w-0 bg-[#d8c799] transition-all duration-500 group-hover:w-12" /></div></Link>)}</div></div></section>
    <section className="relative h-[460px] overflow-hidden bg-[#d8d8d4]">{sections.editorial?.video ? <video src={sections.editorial.video} autoPlay muted loop playsInline className="h-full w-full object-cover object-center" /> : <img src={sections.editorial?.image || "https://images.unsplash.com/photo-1529139574466-a303027c1d8b?auto=format&fit=crop&w=1800&q=90"} alt="أناقة بلا عناء من no name" className="h-full w-full object-cover object-center" />}<div className="absolute inset-0 flex items-center justify-center bg-black/10"><div className="bg-[#d8c799] px-10 py-9 text-center text-white sm:px-16" style={{ backgroundColor: siteSettings.accent }}><h2 className="font-sans text-3xl font-bold">{sections.editorial?.title || "Effortless style"}</h2><p className="mt-3 text-sm text-white/80">{sections.editorial?.description || (isEnglish ? "Thoughtful designs for every moment." : "تصاميم أنيقة تناسب كل لحظة.")}</p><Link to="/shop" className="mt-6 inline-flex border border-white px-7 py-3 text-[11px] font-bold transition hover:bg-white hover:text-black">{isEnglish ? "Shop the collection" : "تسوقي المجموعة"}</Link></div></div></section>
    <section className="border-y border-black/5 bg-white px-5 py-12 lg:px-8"><div className="mx-auto grid max-w-[1100px] grid-cols-2 gap-8 text-center sm:grid-cols-4"><div className="flex flex-col items-center gap-3"><BadgeCheck size={28} strokeWidth={1.3} /><p className="text-[11px] leading-5">{isEnglish ? <>Trusted by<br />10,000+ women</> : <>موثوق به من قبل<br />أكثر من ١٠ آلاف عميلة</>}</p></div><div className="flex flex-col items-center gap-3"><BadgeCheck size={28} strokeWidth={1.3} /><p className="text-[11px] leading-5">{isEnglish ? <>Excellent quality<br />carefully selected</> : <>جودة ممتازة<br />مختارة بعناية</>}</p></div><div className="flex flex-col items-center gap-3"><RotateCcw size={28} strokeWidth={1.3} /><p className="text-[11px] leading-5">{isEnglish ? <>Easy exchanges<br />fast and simple</> : <>عمليات تبديل<br />سهلة وسريعة</>}</p></div><div className="flex flex-col items-center gap-3"><Truck size={28} strokeWidth={1.3} /><p className="text-[11px] leading-5">{isEnglish ? <>Free shipping on orders<br />over EGP 2,500</> : <>شحن مجاني للطلبات<br />فوق ٢٥٠٠ ج.م</>}</p></div></div></section>
    <section className="bg-white px-5 py-16 lg:px-8"><div className="mx-auto max-w-[1240px]"><div className="mb-9 flex items-end justify-between"><div><h2 className="font-sans text-4xl">{sections.discover?.title || "Discover your style"}</h2>{sections.discover?.description && <p className="mt-3 text-[12px] text-black/50">{sections.discover.description}</p>}</div><Sparkles className="text-[#d8c799]" size={22} /></div><div className="-mx-5 flex snap-x snap-mandatory gap-3 overflow-x-auto px-5 pb-4 [scrollbar-width:none] sm:mx-0 sm:px-0">{localizedStories.map((story) => <Link key={story.title} to="/shop" className="group relative aspect-[.7] min-w-[88%] snap-start overflow-hidden sm:min-w-[48%] lg:min-w-[32%]"><video src={story.video} poster={story.image} autoPlay muted loop playsInline preload="metadata" className="h-full w-full object-cover transition duration-700 group-hover:scale-105" aria-label={story.title} /><div className="absolute inset-x-0 bottom-0 bg-gradient-to-t from-black/80 to-transparent p-5 pt-28 text-white"><h3 className="text-lg font-bold">{story.title}</h3><span className="mt-3 inline-flex rounded bg-[#e9e3d7] px-4 py-2 text-[10px] text-black">{isEnglish ? "Shop now" : "تسوقي الآن"} <ArrowLeft className="mr-2" size={13} /></span></div></Link>)}</div></div></section>
    <CollectionShelf title={sections.sets?.title || "Sets"} description={sections.sets?.description} items={sets.length ? sets : catalog} linkLabel={isEnglish ? "Shop sets" : "تسوقي الأطقم"} />
    <CollectionShelf title={sections.tops?.title || "Blouses / shirts"} description={sections.tops?.description} items={tops.length ? tops : catalog} linkLabel={isEnglish ? "Shop tops" : "تسوقي التوبس"} />
    <CollectionShelf title={sections.pants?.title || "Skirts / pants"} description={sections.pants?.description} items={pants.length ? pants : catalog} linkLabel={isEnglish ? "Shop pants" : "تسوقي البناطيل"} />
    <CollectionShelf title={sections.dresses?.title || "Dresses"} description={sections.dresses?.description} items={dresses.length ? dresses : catalog} linkLabel={isEnglish ? "Shop dresses" : "تسوقي الفساتين"} />
  </>;
}
