create extension if not exists pgcrypto;

create table if not exists public.admin_users (
  id uuid primary key default gen_random_uuid(),
  username text not null unique,
  password_hash text not null,
  role text not null default 'editor' check (role in ('admin', 'editor')),
  is_active boolean not null default true,
  last_login_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.admin_sessions (
  id uuid primary key default gen_random_uuid(),
  admin_user_id uuid not null references public.admin_users(id) on delete cascade,
  token_hash text not null unique,
  expires_at timestamptz not null,
  revoked_at timestamptz,
  created_at timestamptz not null default now()
);

create table if not exists public.audit_logs (
  id bigint generated by default as identity primary key,
  admin_user_id uuid references public.admin_users(id) on delete set null,
  action text not null,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists admin_sessions_lookup_idx
  on public.admin_sessions (token_hash, expires_at)
  where revoked_at is null;

create index if not exists audit_logs_admin_created_idx
  on public.audit_logs (admin_user_id, created_at desc);

alter table public.admin_users enable row level security;
alter table public.admin_sessions enable row level security;
alter table public.audit_logs enable row level security;

revoke all on table public.admin_users from anon, authenticated;
revoke all on table public.admin_sessions from anon, authenticated;
revoke all on table public.audit_logs from anon, authenticated;

create table if not exists public.products (
  id text primary key,
  name text not null,
  name_en text,
  description text,
  description_en text,
  category text not null,
  numeric_price numeric(12,2) not null check (numeric_price >= 0),
  original_price numeric(12,2) check (original_price is null or original_price >= 0),
  sale_price numeric(12,2) check (sale_price is null or sale_price >= 0),
  image text not null,
  images jsonb not null default '[]'::jsonb,
  colors jsonb not null default '[]'::jsonb,
  sizes jsonb not null default '[]'::jsonb,
  badge text,
  tag text,
  stock integer not null default 0 check (stock >= 0),
  low_stock_threshold integer not null default 3 check (low_stock_threshold >= 0),
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.site_settings (
  id boolean primary key default true check (id),
  data jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now()
);

create table if not exists public.site_sections (
  key text primary key,
  data jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now()
);

create table if not exists public.page_settings (
  id boolean primary key default true check (id),
  data jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now()
);

create table if not exists public.coupons (
  code text primary key,
  discount numeric(5,2) not null check (discount > 0 and discount <= 100),
  uses integer not null default 0 check (uses >= 0),
  max_uses integer check (max_uses is null or max_uses > 0),
  expires_at timestamptz,
  active boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.customer_profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  full_name text,
  phone text,
  address text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.orders (
  id uuid primary key default gen_random_uuid(),
  customer_id uuid references auth.users(id) on delete set null,
  order_number text not null unique,
  customer_name text not null,
  phone text not null,
  address text not null,
  notes text,
  payment_method text not null check (payment_method in ('cod', 'wallet', 'instapay')),
  transfer_number text,
  receipt text,
  subtotal numeric(12,2) not null check (subtotal >= 0),
  discount_amount numeric(12,2) not null default 0 check (discount_amount >= 0),
  shipping_amount numeric(12,2) not null default 0 check (shipping_amount >= 0),
  total numeric(12,2) not null check (total >= 0),
  coupon_code text references public.coupons(code) on delete set null,
  status text not null default 'new' check (status in ('new', 'processing', 'completed', 'rejected')),
  idempotency_key text not null unique,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.order_items (
  id bigint generated by default as identity primary key,
  order_id uuid not null references public.orders(id) on delete cascade,
  product_id text not null references public.products(id),
  name text not null,
  quantity integer not null check (quantity > 0),
  unit_price numeric(12,2) not null check (unit_price >= 0),
  total numeric(12,2) not null check (total >= 0)
);

create index if not exists products_category_active_idx on public.products (category, active);
create index if not exists orders_status_created_idx on public.orders (status, created_at desc);
create index if not exists order_items_order_idx on public.order_items (order_id);

alter table public.customer_profiles enable row level security;
alter table public.products enable row level security;
alter table public.site_settings enable row level security;
alter table public.site_sections enable row level security;
alter table public.page_settings enable row level security;
alter table public.coupons enable row level security;
alter table public.orders enable row level security;
alter table public.order_items enable row level security;

revoke all on table public.customer_profiles, public.products, public.site_settings, public.site_sections, public.page_settings, public.coupons, public.orders, public.order_items from anon, authenticated;

create or replace function public.create_store_order(
  p_customer_name text,
  p_phone text,
  p_address text,
  p_notes text,
  p_payment_method text,
  p_transfer_number text,
  p_receipt text,
  p_coupon_code text,
  p_idempotency_key text,
  p_items jsonb
) returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_order_id uuid;
  v_order_number text;
  v_subtotal numeric(12,2) := 0;
  v_discount numeric(12,2) := 0;
  v_shipping numeric(12,2) := 0;
  v_total numeric(12,2);
  v_coupon coupons%rowtype;
  v_item jsonb;
  v_product products%rowtype;
  v_quantity integer;
  v_unit_price numeric(12,2);
begin
  if p_idempotency_key is null or length(trim(p_idempotency_key)) < 16 then
    raise exception 'invalid idempotency key' using errcode = '22023';
  end if;

  select id, order_number, total into v_order_id, v_order_number, v_total
  from orders where idempotency_key = p_idempotency_key;
  if v_order_id is not null then
    return jsonb_build_object('id', v_order_id, 'order_number', v_order_number, 'total', v_total);
  end if;

  if jsonb_typeof(p_items) <> 'array' or jsonb_array_length(p_items) = 0 then
    raise exception 'order must contain items' using errcode = '22023';
  end if;
  if (select count(*) from jsonb_array_elements(p_items)) <> (select count(distinct value->>'productId') from jsonb_array_elements(p_items)) then
    raise exception 'duplicate product' using errcode = '22023';
  end if;

  for v_item in select * from jsonb_array_elements(p_items) loop
    v_quantity := (v_item->>'quantity')::integer;
    if v_quantity is null or v_quantity < 1 or v_quantity > 99 then
      raise exception 'invalid quantity' using errcode = '22023';
    end if;
    select * into v_product from products where id = v_item->>'productId' and active = true for update;
    if not found or v_product.stock < v_quantity then
      raise exception 'product unavailable' using errcode = 'P0001';
    end if;
    v_unit_price := coalesce(v_product.sale_price, v_product.numeric_price);
    v_subtotal := v_subtotal + (v_unit_price * v_quantity);
  end loop;

  if nullif(trim(p_coupon_code), '') is not null then
    select * into v_coupon from coupons where code = upper(trim(p_coupon_code)) and active = true for update;
    if not found or (v_coupon.expires_at is not null and v_coupon.expires_at <= now()) or (v_coupon.max_uses is not null and v_coupon.uses >= v_coupon.max_uses) then
      raise exception 'invalid coupon' using errcode = 'P0001';
    end if;
    v_discount := round(v_subtotal * v_coupon.discount / 100, 2);
  end if;

  v_shipping := case when v_subtotal >= 2500 then 0 else 80 end;
  v_total := greatest(0, v_subtotal - v_discount + v_shipping);
  v_order_number := 'NN-' || to_char(clock_timestamp(), 'YYYYMMDDHH24MISSMS');

  insert into orders (order_number, customer_name, phone, address, notes, payment_method, transfer_number, receipt, subtotal, discount_amount, shipping_amount, total, coupon_code, idempotency_key)
  values (v_order_number, trim(p_customer_name), trim(p_phone), trim(p_address), nullif(trim(p_notes), ''), p_payment_method, nullif(trim(p_transfer_number), ''), nullif(trim(p_receipt), ''), v_subtotal, v_discount, v_shipping, v_total, nullif(upper(trim(p_coupon_code)), ''), p_idempotency_key)
  returning id into v_order_id;

  for v_item in select * from jsonb_array_elements(p_items) loop
    v_quantity := (v_item->>'quantity')::integer;
    select * into v_product from products where id = v_item->>'productId' for update;
    v_unit_price := coalesce(v_product.sale_price, v_product.numeric_price);
    insert into order_items (order_id, product_id, name, quantity, unit_price, total, size, color)
    values (v_order_id, v_product.id, v_product.name, v_quantity, v_unit_price, v_unit_price * v_quantity, nullif(trim(v_item->>'size'), ''), nullif(trim(v_item->>'color'), ''));
    update products set stock = stock - v_quantity, updated_at = now() where id = v_product.id;
  end loop;

  if v_coupon.code is not null then
    update coupons set uses = uses + 1 where code = v_coupon.code;
  end if;

  return jsonb_build_object('id', v_order_id, 'order_number', v_order_number, 'total', v_total);
exception when unique_violation then
  select id, order_number, total into v_order_id, v_order_number, v_total from orders where idempotency_key = p_idempotency_key;
  if v_order_id is not null then
    return jsonb_build_object('id', v_order_id, 'order_number', v_order_number, 'total', v_total);
  end if;
  raise;
end;
$$;

revoke all on function public.create_store_order(text, text, text, text, text, text, text, text, text, jsonb) from public, anon, authenticated;

grant execute on function public.create_store_order(text, text, text, text, text, text, text, text, text, jsonb) to service_role;

insert into storage.buckets (id, name, public)
values ('receipts', 'receipts', false)
on conflict (id) do update set public = false;
